
team_index:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:index

team_new:
    path: /new
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:new

team_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: AppBundle:Team:new

team_view:
    path: /view/{team_id}/{slug}
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:view
    requirements:
        team_id: \d+

team_edit:
    path: /edit/{team_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:edit
    requirements:
        team_id: \d+

team_update:
    path: /update/{team_id}
    methods: [POST]
    defaults:
        _controller: AppBundle:Team:edit
    requirements:
        team_id: \d+

team_delete:
    path: /delete
    methods: [POST]
    defaults:
        _controller: AppBundle:Team:delete

team_check_deck:
    path: /check_deck/{deck_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:checkDeck
    requirements:
        deck_id: \d+

team_campaign_add:
    path: /add_campaign/{team_id}
    methods: [POST]
    defaults:
        _controller: AppBundle:Team:addCampaign
    requirements:
        team_id: \d+

team_campaign_edit:
    path: /campaign/{campaignlist_id}/edit
    methods: [GET, POST]
    defaults:
        _controller: AppBundle:Team:editCampaignList
    requirements:
        campaignlist_id: \d+

team_campaign_scenario_stats:
    path: /campaign/{campaignlist_id}/scenario/{scenario_code}/stats
    methods: [GET]
    defaults:
        _controller: AppBundle:Team:scenarioStats
    requirements:
        campaignlist_id: \d+

